project_id = "clwruolkostoirdwnnuy"

[functions.activate-account]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.api-resources]
verify_jwt = false

[functions.api-tasks]
verify_jwt = false

[functions.api-calendar-events]
verify_jwt = false

[functions.api-messages]
verify_jwt = false

[functions.api-courses]
verify_jwt = false

[functions.api-reg-order]
verify_jwt = false

[functions.api-reg-split]
verify_jwt = false

[functions.api-reg-payment]
verify_jwt = false

[functions.api-resource-trial]
verify_jwt = false

[functions.api-resource-trial-callback]
verify_jwt = false

[functions.api-reg-enrollments]
verify_jwt = false
