import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-api-key",
};

interface PersonInfo {
  name: string;
  phone?: string;
  email?: string;
}

interface RequestBody {
  order_no: string;
  course_codes: string[];        // reg_courses.course_code array
  persons: PersonInfo[];          // 1~3 persons
  payment_status?: string;        // pending | paid
  paid_at?: string;
  payment_method?: string;
  total_amount?: number;
  discount_plan?: string;         // single | duo | trio
  invoice_type?: string;
  invoice_title?: string;
  invoice_number?: string;
  dealer_id?: string;
  notes?: string;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    // Verify API key
    const apiKey = req.headers.get("x-api-key");
    const expectedKey = Deno.env.get("API_INTEGRATION_KEY");
    if (!apiKey || apiKey !== expectedKey) {
      return new Response(JSON.stringify({ error: "Invalid API key" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body: RequestBody = await req.json();

    // Validate required fields
    if (!body.order_no || !body.course_codes?.length || !body.persons?.length) {
      return new Response(JSON.stringify({
        error: "Missing required fields: order_no, course_codes, persons",
      }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (body.persons.length > 3) {
      return new Response(JSON.stringify({ error: "Maximum 3 persons per order" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (body.course_codes.length > 4) {
      return new Response(JSON.stringify({ error: "Maximum 4 courses per order" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Validate each person has a name
    for (let i = 0; i < body.persons.length; i++) {
      if (!body.persons[i].name?.trim()) {
        return new Response(JSON.stringify({ error: `Person ${i + 1} must have a name` }), {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const adminClient = createClient(supabaseUrl, serviceRoleKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    // 1. Look up courses by course_code
    const { data: courses, error: courseErr } = await adminClient
      .from("reg_courses")
      .select("id, course_code, course_name, course_type, price")
      .in("course_code", body.course_codes);

    if (courseErr) throw courseErr;

    if (!courses || courses.length !== body.course_codes.length) {
      const foundCodes = courses?.map((c) => c.course_code) || [];
      const missing = body.course_codes.filter((c) => !foundCodes.includes(c));
      return new Response(JSON.stringify({
        error: `Courses not found: ${missing.join(", ")}`,
      }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Build course lookup map
    const courseMap = new Map(courses.map((c) => [c.course_code, c]));

    // 2. Find or create reg_members for each person
    const memberIds: string[] = [];
    for (const person of body.persons) {
      let memberId: string | null = null;

      // Try to find existing member by email or by name+phone
      if (person.email) {
        const { data: existing } = await adminClient
          .from("reg_members")
          .select("id")
          .eq("email", person.email)
          .maybeSingle();
        if (existing) memberId = existing.id;
      }

      if (!memberId && person.phone) {
        const { data: existing } = await adminClient
          .from("reg_members")
          .select("id")
          .eq("name", person.name)
          .eq("phone", person.phone)
          .maybeSingle();
        if (existing) memberId = existing.id;
      }

      if (!memberId) {
        // Create new member (member_no auto-generated by trigger)
        const { data: newMember, error: memberErr } = await adminClient
          .from("reg_members")
          .insert({
            name: person.name.trim(),
            phone: person.phone || null,
            email: person.email || null,
          })
          .select("id")
          .single();
        if (memberErr) throw memberErr;
        memberId = newMember.id;
      }

      memberIds.push(memberId);
    }

    // 3. Create reg_order
    const courseSnapshot = body.course_codes.map((code) => {
      const c = courseMap.get(code)!;
      return { course_code: c.course_code, course_name: c.course_name, price: c.price };
    });

    const courseIds = body.course_codes.map((code) => courseMap.get(code)!.id);

    const orderInsert: Record<string, unknown> = {
      order_no: body.order_no,
      course_ids: courseIds,
      course_snapshot: courseSnapshot,
      payment_status: body.payment_status || "pending",
      paid_at: body.paid_at || null,
      payment_method: body.payment_method || null,
      total_amount: body.total_amount || 0,
      discount_plan: body.discount_plan || null,
      invoice_type: body.invoice_type || null,
      invoice_title: body.invoice_title || null,
      invoice_number: body.invoice_number || null,
      dealer_id: body.dealer_id || null,
      notes: body.notes || null,
    };

    // Map persons to p1/p2/p3
    for (let i = 0; i < body.persons.length; i++) {
      const p = body.persons[i];
      const idx = i + 1;
      orderInsert[`p${idx}_name`] = p.name;
      orderInsert[`p${idx}_phone`] = p.phone || null;
      orderInsert[`p${idx}_email`] = p.email || null;
    }

    const { data: order, error: orderErr } = await adminClient
      .from("reg_orders")
      .insert(orderInsert)
      .select("id")
      .single();

    if (orderErr) {
      if (orderErr.message.includes("duplicate") || orderErr.message.includes("unique")) {
        return new Response(JSON.stringify({
          error: `訂單編號已存在: ${body.order_no}`,
          exists: true,
        }), {
          status: 409,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      throw orderErr;
    }

    // 4. Create reg_enrollments: each person × each course
    const enrollments: Record<string, unknown>[] = [];
    for (const memberId of memberIds) {
      for (const courseCode of body.course_codes) {
        const course = courseMap.get(courseCode)!;
        enrollments.push({
          order_id: order.id,
          member_id: memberId,
          course_id: course.id,
          course_type: course.course_type,
          status: body.payment_status === "paid" ? "enrolled" : "enrolled",
          payment_status: body.payment_status || "pending",
          paid_at: body.paid_at || null,
          invoice_title: body.invoice_title || null,
          dealer_id: body.dealer_id || null,
        });
      }
    }

    const { data: insertedEnrollments, error: enrollErr } = await adminClient
      .from("reg_enrollments")
      .insert(enrollments)
      .select("id, member_id, course_id");

    if (enrollErr) throw enrollErr;

    return new Response(JSON.stringify({
      success: true,
      data: {
        order_id: order.id,
        order_no: body.order_no,
        member_ids: memberIds,
        enrollments_count: insertedEnrollments?.length || 0,
        message: "報名資料已建立",
      },
    }), {
      status: 201,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: unknown) {
    console.error("Registration callback error:", err);
    const message = err instanceof Error ? err.message : JSON.stringify(err);
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
