// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clwruolkostoirdwnnuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsd3J1b2xrb3N0b2lyZHdubnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNjI2ODAsImV4cCI6MjA4NDkzODY4MH0.e9AyEXoUaPoTLn9U-jPVUb9QDYVPmcCFISxuHjrb5ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});